# Generated by Django 6.0 on 2025-12-31 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_win_name', models.CharField(max_length=200)),
                ('adm_win_sts', models.CharField(max_length=200)),
                ('adm_win_start', models.CharField(max_length=100)),
                ('adm_win_close', models.CharField(max_length=100)),
                ('adm_elg', models.CharField(max_length=200)),
                ('nxt_adm_win_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=300)),
                ('d_desc', models.CharField(max_length=1000)),
                ('d_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('f_img', models.ImageField(blank=True, null=True, upload_to='faculty/')),
                ('f_sub', models.CharField(blank=True, max_length=100, null=True)),
                ('f_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='core.departments')),
            ],
        ),
    ]
