# Generated by Django 6.0 on 2026-01-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admission_departments_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='nxt_adm_win_name',
        ),
        migrations.AddField(
            model_name='programs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='adm_elg',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='admission',
            name='adm_win_close',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='admission',
            name='adm_win_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='admission',
            name='adm_win_sts',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='departments',
            name='d_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='departments',
            name='d_num',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='f_sub',
        ),
        migrations.AlterField(
            model_name='programs',
            name='p_desc',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='faculty',
            name='f_sub',
            field=models.ManyToManyField(blank=True, to='core.subjects'),
        ),
    ]
