# Generated by Django 6.0 on 2026-01-17 10:14

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subjects_delete_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('previous_qualification', models.CharField(choices=[('high_school', 'High School'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate')], max_length=50)),
                ('certificates', models.FileField(upload_to='certificates/')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('phone_country_code', models.CharField(max_length=10)),
                ('local_phone_number', models.CharField(max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.programs')),
            ],
        ),
    ]
