# Generated by Django 6.0 on 2026-01-19 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_admissionapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='f_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='core.departments', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='f_img',
            field=models.ImageField(blank=True, null=True, upload_to='faculty/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='f_name',
            field=models.CharField(max_length=200, verbose_name='Faculty Name'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='f_sub',
            field=models.ManyToManyField(blank=True, to='core.subjects', verbose_name='Subjects'),
        ),
    ]
