# Generated by Django 5.2.10 on 2026-01-30 19:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_faculty_f_dep_alter_faculty_f_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='f_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Profile Image'),
        ),
    ]
