# Generated by Django 5.2.10 on 2026-01-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_faculty_f_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='f_sub',
            field=models.ManyToManyField(blank=True, related_name='faculties', to='core.subject', verbose_name='Subjects'),
        ),
    ]
